// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrbouetcqtxlmlpqboqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyYm91ZXRjcXR4bG1scHFib3FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NDQyOTcsImV4cCI6MjA2ODAyMDI5N30.VEBhVgmps5fX8CTTxTo0GbSLTw33MtTMeXqs2ndGRZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});